name: Create Release
description: Create Release for the apps Build

runs:
  using: composite
  steps:
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        # Download artifacts from other platforms
        mkdir -p artifacts
        gh run download --dir artifacts --pattern '*.zip'

        # Create release with all artifacts
        assets=()
        for zip in artifacts/*.zip *.zip; do
          if [ -f "$zip" ]; then
            assets+=("$zip")
          fi
        done

        gh release create "${{ github.ref_name }}" \
          --title "Release ${{ github.ref_name }}" \
          --draft=false \
          --prerelease=false \
          "${assets[@]}"
      