name: Gen Artifact
description: Gen Artifact for the apps Build

runs:
  using: composite
  steps:
    - name: ci-setup | Create artifact archive
      shell: bash
      run: |
        cd build
        if [ "${{ runner.os }}" == "Windows" ]; then
          7z a ../${{ matrix.artifact_name }}.zip ${{ matrix.artifact_glob }}
        else
          zip -r ../${{ matrix.artifact_name }}.zip ${{ matrix.artifact_glob }}
        fi
      
    - name: logs | dir
      shell: bash
      run: |
        pwd
        ls
    
    - name: ci-setup | Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}.zip
        if-no-files-found: error
      
    - name: logs | dir
      shell: bash
      run: |
        pwd
        ls
