name: playground | deployer

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    name: data_center | TVA
    if: ${{ inputs.CALLER == 'timeline' }}
    uses: vezham/vezham-frontend/.github/workflows/apps_internals/playground.helper.yml@deployer
    secrets:
      GCP_PROJECT_ID: ${{ secrets.PLAYGROUND_TVA_GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.PLAYGROUND_TVA_GCP_SA_KEY }}
    with:
      GIT_BRANCH: ${{ inputs.CALLER }}
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: playground
      BASE_API_URL: mock
      MOCK_API_URL: https://dev.playground.mock.vezham.com
      APP_API_URL: https://dev.api.vezham.com
