name: Upload Logs to artifact
description: Upload the logs for debugging

runs:
  using: composite
  steps:
    - name: logs | dir
      shell: bash
      run: |
        echo "logs -> artifact"
        pwd
        ls

    - name: ci-setup | Upload Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: publish-logs
        path: .vezham/
        retention-days: 30
