name: Upload Logs to artifact
description: Upload the logs for debugging

runs:
  using: composite
  steps:
    - name: logs | dir
      shell: bash
      run: |
        cp -R .vezham/ v0xCI/
        echo "logs -> artifact"
        pwd
        ls

    - name: ci-setup | Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: v0xCI-artifact
        path: v0xCI/
        retention-days: 30
