name: Upload Logs to artifact
description: Upload the logs for debugging

runs:
  using: composite
  steps:
    - name: logs | dir
      shell: bash
      run: |
        pwd
        ls
        mkdir -p .vezham
        echo "chk -> "
        pwd
        ls
        cd .vezham/
        pwd
        ls
    
    - name: logs | e2e
      continue-on-error: true
      shell: bash
      run: |
        mkdir -p .vezham
        cp -R dist/.playwright/ .vezham/playwright/
        echo "logs -> playwright-report"

    - name: logs | dir
      shell: bash
      run: |
        mkdir -p .vezham
        cp -R .vezham/ v0xCI/
        echo "logs -> artifact"
        pwd
        cd .vezham/
        ls

    - name: ci-setup | Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: v0xCI-artifact
        path: v0xCI/
        retention-days: 30
