name: Setup Env var
description: Setup .env vars

runs:
  using: composite
  steps:
    - name: os 
      shell: bash
      run: echo ${{ runner.os }} # Linux, macOS, Windows
    
    # - name: setup | .env vars
    #   uses: SpicyPizza/create-envfile@v1.3
    #   with:
    #     directory: ${{ env.ENTRY_POINT }}
    #     # envkey_V_IS_PREVIEW: ${{ inputs.IS_PREVIEW }}
    #     envkey_V_IS_DEBUG: ${{ inputs.IS_DEBUG }}
    #     # envkey_V_IS_BETA: ${{ inputs.IS_BETA }}
    #     envkey_V_APP_NAME: ${{ inputs.APP_NAME }}
    #     envkey_V_CONFIG_APP: ${{ inputs.CONFIG_APP }}
    #     envkey_V_CONFIG_AUTHOR: ${{ inputs.CONFIG_AUTHOR }}
    #     envkey_V_CONFIG_ICON: ${{ inputs.CONFIG_ICON }}
    #     envkey_V_APP_URL: ${{ inputs.APP_URL }}
    #     envkey_V_APP_MENU: ${{ inputs.APP_MENU }}
    
    # - name: ci-setup | gen $ENV_VARS
    #   id: gen-env-tokens
    #   run: |
    #     {
    #       echo "V_IS_DEBUG=${{ inputs.IS_DEBUG }}"
    #       echo "V_APP_NAME=${{ inputs.APP_NAME }}"
    #       echo "V_CONFIG_APP=${{ inputs.CONFIG_APP }}"
    #       echo "V_CONFIG_AUTHOR=${{ inputs.CONFIG_AUTHOR }}"
    #       echo "V_CONFIG_ICON=${{ inputs.CONFIG_ICON }}"
    #       echo "V_APP_URL=${{ inputs.APP_URL }}"
    #       echo "V_APP_MENU=${{ inputs.APP_MENU }}"
    #     } >> $GITHUB_ENV
    
    # - name: logs | dir
    #   shell: bash
    #   run: |
    #     pwd
    #     ls
