name: Gen Build
description: Gen Build for the apps

inputs:
  platform:
    description: 'Platform to setup certificates for'
    required: true

runs:
  using: composite
  steps:
    # - name: setup | app-icon - ImageMagick
    #   if: runner.os == 'Windows'
    #   uses: mfinelli/setup-imagemagick@v3

    - name: setup | app-icon
      uses: vezham/v0xFE-deployer/.github/apps-desktop-actions/setup-icons@timeline
      env:
        APP_ICON_PATH: ${{ env.APP_ICON_PATH }} # https://static.cdn.vezham.com/icons/favicon.png 
    
    - name: cli | package
      shell: bash
      run: |
        pnpm package

    # - name: cli | build
    #   shell: bash
    #   run: |
    #     pnpm make

    - name: cli | publish
      shell: bash
      run: |
        pnpm run publish --no-git-checks

    - name: logs | dir
      shell: bash
      run: |
        pwd
        cd build
        pwd
        ls
