name: Gen Build
description: Gen Build for the apps

runs:
  using: composite
  steps:
    - name: cli | package
      shell: bash
      run: |
        pnpm package

    - name: cli | package - no shell
      run: |
        pnpm package
    
    # - name: cli | build
    #   run: |
    #     pnpm make
