name: Gen Build
description: Gen Build for the apps

runs:
  using: composite
  steps:
    - name: setup | app-icon
      uses: vezham/v0xFE-deployer/.github/apps-desktop-actions/setup-icons@timeline
      env:
        APP_ICON_PATH: ${{ env.APP_ICON_PATH }} # https://static.cdn.vezham.com/icons/favicon.png 
    
    - name: cli | package
      shell: bash
      run: |
        pnpm package
        pnpm run make

    # - name: cli | build & publish
    #   shell: bash
    #   run: |
    #     pnpm run make
    #     pnpm run publish
    #     pnpm run publish --no-git-checks

    # - name: logs | dir
    #   shell: bash
    #   run: |
    #     pwd
    #     cd build
    #     pwd
    #     ls
