# wjdlz | TODO: vercel cloud-setup
      # - name: gcp | cloud CLI
      #   uses: w9jds/firebase-action@v12.9.0
      #   with:
      #     args: deploy --only hosting
      #   env:
      #     PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      #     GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}