name: Gen DX App URL
description: Gen $DX_APP_URL

runs:
  using: composite
  steps:
    - name: ci-setup | SHA
      uses: vezham/v0xFE-deployer/.github/common-actions/setup-sha@timeline
    
    - name: ci-setup | gen DX_APP_URL
      id: gen-dx-app-url
      shell: bash
      # echo 'DX_APP_URL=${{ env.DX_APP_NAME }}-${{ env.BRANCH }}-${{ env.SHA }}-${{ github.actor }}.ui.dx.tva.v0x.in' >> $GITHUB_ENV
      run: |
        echo 'DX_APP_URL=${{ env.DX_APP_NAME }}-${{ env.BRANCH }}-${{ env.SHA }}' >> $GITHUB_ENV
