name: Setup checkout
description: Sets up repo & branch

inputs:
  GIT_REPO:
    required: true
    type: string
  GIT_BRANCH:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: checkout | ${{ inputs.REPO }}@${{ inputs.BRANCH }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.REPO }}
        ref: ${{ inputs.BRANCH }}
        fetch-depth: 0
        submodules: false
    
    - name: Setup SSH for submodules
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SUBMODULE_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Init and update submodules
      run: |
        git submodule sync
        git submodule update --init --recursive
