name: Setup App Icons
description: Downloads and prepares app icons in required formats

runs:
  using: composite
  steps:
    - name: Create images directory
      shell: bash
      run: mkdir -p images

    - name: Download and prepare icons
      shell: bash
      run: |
        # Download icon from cloud storage
        if [ -z "$APP_ICON_PATH" ]; then
          echo "Error: APP_ICON_PATH environment variable is not set"
          exit 1
        fi

        curl -o "images/temp_icon.png" "$APP_ICON_PATH"

        # Convert to required formats
        if [ "${{ runner.os }}" == "macOS" ]; then
          # Convert to icns for macOS
          sips -s format png "images/temp_icon.png" --out "images/icon.png"
          iconutil -c icns "images/icon.png" -o "images/icon.icns"
        elif [ "${{ runner.os }}" == "Windows" ]; then
          # Convert to ico for Windows
          convert "images/temp_icon.png" -define icon:auto-resize=256,128,64,48,32,16 "images/icon.ico"
        fi

        # Keep PNG version for all platforms
        cp "images/temp_icon.png" "images/icon.png"
        rm "images/temp_icon.png"
