name: apps-desktop/suites-one | DC

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    name: dc/TVA
    if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@timeline')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: timeline
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"tva","status":"stable"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'
      
  dev:
    name: dc/dev
    if: ${{ inputs.CALLER == 'deploy/dev' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@dev')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/dev
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"dev","status":"unstable"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'

  qa:
    name: dc/qa
    if: ${{ inputs.CALLER == 'deploy/qa' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@qa')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/qa
      IS_BETA: true
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"qa","status":"alpha"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'

  preview:
    name: dc/preview
    if: ${{ inputs.CALLER == 'deploy/preview' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@preview')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/preview
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"preview","status":"beta"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'
      
  prod:
    name: dc/prod
    if: ${{ inputs.CALLER == 'deploy/prod' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@prod')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/prod
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"prod","status":"stable"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'
