name: apps-desktop/suites-one | DC

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' || startsWith(inputs.CALLER, '@suites-one') }}
    name: suites/One
    runs-on: ubuntu-latest
    outputs:
      timeline: ${{ steps.filter.outputs.timeline }}
      dev: ${{ steps.filter.outputs.dev }}
      qa: ${{ steps.filter.outputs.qa }}
      preview: ${{ steps.filter.outputs.preview }}
      prod: ${{ steps.filter.outputs.prod }}
    steps:
      - name: filter | ${{ inputs.CALLER }}
        id: filter
        shell: bash
        run: |
          {
            "timeline=${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@timeline/ci')  }}"
            "dev=${{ inputs.CALLER == 'deploy/dev' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@dev/ci')  }}"
            "qa=${{ inputs.CALLER == 'deploy/qa' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@qa/ci')  }}"
            "preview=${{ inputs.CALLER == 'deploy/preview' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@preview/ci')  }}"
            "prod=${{ inputs.CALLER == 'deploy/prod' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@prod/ci')  }}"
          } >> $GITHUB_OUTPUT
          
  timeline:
    needs: tva
    if: ${{ needs.tva.outputs.timeline == true || needs.tva.outputs.timeline == 'true' }}
    name: dc/timeline
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: timeline
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"tva","status":"stable"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'
      
  dev:
    needs: tva
    if: ${{ needs.tva.outputs.dev == 'true' }}
    name: dc/dev
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/dev
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"dev","status":"unstable"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'

  qa:
    needs: tva
    if: ${{ needs.tva.outputs.qa == 'true' }}
    name: dc/qa
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/qa
      IS_BETA: true
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"qa","status":"alpha"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'

  preview:
    needs: tva
    if: ${{ needs.tva.outputs.preview == 'true' }}
    name: dc/preview
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/preview
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"preview","status":"beta"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'
      
  prod:
    needs: tva
    if: ${{ needs.tva.outputs.prod == 'true' }}
    name: dc/prod
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/prod
      APP_NAME: vezham-one
      CONFIG_APP: '{"name":"Vezham One","category":"public.app-category.productivity","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"suites.one","env":"prod","status":"stable"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/suites/one/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://one.suites.cloud.vezham.com"}
      APP_MENU: '{"help_center":"https://help.vezham.com/suites/one"}'
