name: apps-desktop/apps-messenger | DC

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    name: TVA
    if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' || startsWith(inputs.CALLER, '@apps-messenger') }}
    runs-on: ubuntu-latest
    steps:
      - name: os 
        shell: bash
        run: echo ${{ runner.os }} # Linux, macOS, Windows

  timeline:
    name: dc/timeline
    needs: tva
    if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@timeline/ci')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: timeline
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: vezham-messenger
      CONFIG_APP: '{"name":"Vezham Messenger","category":"public.app-category.social-networking","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"apps.messenger","env":"tva","status":"stable"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/apps/messenger/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://messenger.apps.cloud.vezham.com"}
      APP_MENU: '{"help_center":"help.vezham.com/apps/messenger"}'
      
  dev:
    name: dc/dev
    if: ${{ inputs.CALLER == 'deploy/dev' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@dev/ci')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/dev
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: vezham-messenger
      CONFIG_APP: '{"name":"Vezham Messenger","category":"public.app-category.social-networking","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"apps.messenger","env":"dev","status":"unstable"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/apps/messenger/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://messenger.apps.cloud.vezham.com"}
      APP_MENU: '{"help_center":"help.vezham.com/apps/messenger"}'

  qa:
    name: dc/qa
    if: ${{ inputs.CALLER == 'deploy/qa' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@qa/ci')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/qa
      IS_BETA: true
      APP_NAME: vezham-messenger
      CONFIG_APP: '{"name":"Vezham Messenger","category":"public.app-category.social-networking","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"apps.messenger","env":"qa","status":"alpha"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/apps/messenger/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://messenger.apps.cloud.vezham.com"}
      APP_MENU: '{"help_center":"help.vezham.com/apps/messenger"}'

  preview:
    name: dc/preview
    if: ${{ inputs.CALLER == 'deploy/preview' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@preview/ci')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/preview
      APP_NAME: vezham-messenger
      CONFIG_APP: '{"name":"Vezham Messenger","category":"public.app-category.social-networking","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"apps.messenger","env":"preview","status":"beta"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/apps/messenger/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://messenger.apps.cloud.vezham.com"}
      APP_MENU: '{"help_center":"help.vezham.com/apps/messenger"}'
      
  prod:
    name: dc/prod
    if: ${{ inputs.CALLER == 'deploy/prod' || inputs.CALLER == 'scheduler' || endsWith(inputs.CALLER, '@prod/ci')  }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: deploy/prod
      APP_NAME: vezham-messenger
      CONFIG_APP: '{"name":"Vezham Messenger","category":"public.app-category.social-networking","app_version":"1.0.5","build_version":"v0x25","pkg_bundle_id":"com.vezham","app_bundle_id":"apps.messenger","env":"prod","status":"stable"}'
      CONFIG_AUTHOR: '{"copyright":"✌️ Vezham © 2025","info":{"v0xauthor":"v0xfe-desktop-apps"}}'
      CONFIG_ICON: '{"host":"https://static.cdn.vezham.com","path":"/apps/messenger/icons"}'
      APP_URL: '{"__type":"prod","local":"http://localhost:3000","preview":"http://localhost:8080","prod":"https://lab5-ic-web-vezham--policy-center-timeline-61b5bb1-vgfywiin.web.app"}'
      # APP_URL: {"__type":"prod","prod":"https://messenger.apps.cloud.vezham.com"}
      APP_MENU: '{"help_center":"help.vezham.com/apps/messenger"}'
