name: accounts-mock | deployer

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    name: dc/TVA
    if: ${{ inputs.CALLER == 'timeline' }}
    uses: vezham/v0xFE-deployer/.github/workflows/accounts-mock.helper.yml@timeline
    secrets:
      VERCEL_ORG_ID: ${{ secrets.ACCOUNTS_MOCK_TVA_VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.ACCOUNTS_MOCK_TVA_VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.ACCOUNTS_MOCK_TVA_VERCEL_TOKEN }}
    with:
      GIT_BRANCH: ${{ inputs.CALLER }}
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: accounts-mock
