name: apps-desktop | deployer

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    name: dc/TVA
    if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' }}
    uses: vezham/v0xFE-deployer/.github/workflows/apps-desktop.helper.yml@timeline
    with:
      GIT_BRANCH: ${{ inputs.CALLER }}
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: accounts
  