name: apps-desktop | helper

on:
  workflow_call:
    inputs:
      GIT_REPO:
        required: false
        type: string
      GIT_BRANCH:
        required: false
        type: string
      IS_PREVIEW:
        required: false
        type: boolean
        default: false
      IS_DEBUG:
        required: false
        type: boolean
        default: false
      IS_BETA:
        required: false
        type: boolean
        default: false
      APP_NAME:
        type: string
      # wjdlz/NOTE: custom-fields

      CONFIG_APP:
        required: true
        type: string
      CONFIG_AUTHOR:
        required: true
        type: string
      CONFIG_ICON:
        required: true
        type: string
      APP_URL:
        required: true
        type: string
      APP_MENU:
        required: true
        type: string

env:
  REPO: ${{ inputs.GIT_REPO || 'vezham/v0xFE-apps-desktop' }}
  BRANCH: ${{ inputs.GIT_BRANCH || 'timeline' }}
  CI_DIR: ./v/bin/ci
  ENTRY_POINT: ./
  # DX_APP_PATH:
  # DX_APP_NAME:
  # NX_APP_NAME:

jobs:
  bnd:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20]
        pnpm-version: [9.6.0]
        include:
          - os: ubuntu-latest
            artifact_name:  ${{ inputs.APP_NAME }}-linux-artifacts
            # artifact_glob: 'make/**/*.{deb,rpm,AppImage}'
            artifact_glob: '*-linux-x64'
          - os: macos-latest
            artifact_name: ${{ inputs.APP_NAME }}-macos-artifacts
            # artifact_glob: 'make/**/*.dmg'
            # artifact_glob: 'make/zip/darwin/arm64/*.zip'
            artifact_glob: '*-darwin-arm64'
          - os: windows-latest
            artifact_name: ${{ inputs.APP_NAME }}-windows-artifacts
            # artifact_glob: 'make/**/*.exe'
            artifact_glob: '*-win32-x64'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: action | checkout | ${{ env.REPO }}@${{ env.BRANCH }}
        uses: vezham/v0xFE-deployer/.github/common-actions/setup-checkout@timeline
        with:
          GIT_REPO: ${{ env.REPO }}
          GIT_BRANCH: ${{ env.BRANCH }}
        
      - name: action | node & pnpm
        uses: vezham/v0xFE-deployer/.github/common-actions/setup-install@timeline

      - name: action | gen $DX_APP_URL
        uses: vezham/v0xFE-deployer/.github/common-actions/gen-dx-app-url@timeline

      - name: action | gen $ENV_VARS
        uses: vezham/v0xFE-deployer/.github/apps-desktop-actions/setup-env@timeline
      
      - name: action | gen-build
        uses: vezham/v0xFE-deployer/.github/apps-desktop-actions/gen-build@timeline

      - name: action | gen-artifact
        uses: vezham/v0xFE-deployer/.github/apps-desktop-actions/gen-artifact@timeline
