name: apps-desktop | deployer

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  suites-one:
    # if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' || startsWith(inputs.CALLER, '@suites-one') }}
    name: suites/One
    uses: vezham/v0xFE-deployer/.github/workflows/-dc-apps-desktop.suites-one.yml@timeline
    with:
      CALLER: ${{ inputs.CALLER }}
  
  suites-hq:
    # if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' || startsWith(inputs.CALLER, '@suites-hq') }}
    name: suites/HQ
    uses: vezham/v0xFE-deployer/.github/workflows/-dc-apps-desktop.suites-hq.yml@timeline
    with:
      CALLER: ${{ inputs.CALLER }}

  apps-messenger:
    if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' || startsWith(inputs.CALLER, '@apps-messenger') }}
    name: apps/Messenger
    uses: vezham/v0xFE-deployer/.github/workflows/-dc-apps-desktop.apps-messenger.yml@timeline
    with:
      CALLER: ${{ inputs.CALLER }}
