name: business | deployer

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    name: dc/TVA
    if: ${{ inputs.CALLER == 'timeline' || inputs.CALLER == 'scheduler' }}
    uses: vezham/v0xFE-deployer/.github/workflows/business.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.BUSINESS_TVA_GCP_SA_KEY }}
    with:
      GIT_BRANCH: ${{ inputs.CALLER }}
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: business
      APP_API_URL: https://dev.api.vezham.com
      APP_IAM_URL: https://preview.iam.vezham.com
      APP_ACCOUNTS_URL: https://preview.accounts.vezham.com
      APP_BUSINESS_URL: https://preview.business.vezham.com
      APP_HQ_URL: https://preview.hq.vezham.com
      APP_IS_SANDBOX: true
      APP_SANDBOX_API_URL: https://sandbox.api.vezham.com
      APP_DC_API_URL: https://{DC}.api.vezham.com
      
  dev:
    name: dc/dev
    if: ${{ inputs.CALLER == 'deploy/dev' || inputs.CALLER == '-scheduler' }}
    uses: vezham/v0xFE-deployer/.github/workflows/business.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.BUSINESS_DEV_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/dev
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: business
      APP_API_URL: https://dev.api.vezham.com
      APP_IAM_URL: https://dev.iam.vezham.com
      APP_ACCOUNTS_URL: https://dev.accounts.vezham.com
      APP_BUSINESS_URL: https://dev.business.vezham.com
      APP_HQ_URL: https://dev.hq.vezham.com
      APP_IS_SANDBOX: true
      APP_SANDBOX_API_URL: https://sandbox.api.vezham.com
      APP_DC_API_URL: https://{DC}.api.vezham.com

  qa:
    name: dc/qa
    if: ${{ inputs.CALLER == 'deploy/qa' || inputs.CALLER == '-scheduler' }}
    uses: vezham/v0xFE-deployer/.github/workflows/business.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.BUSINESS_QA_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/qa
      IS_BETA: true
      APP_NAME: business
      APP_API_URL: https://qa.api.vezham.com
      APP_IAM_URL: https://qa.iam.vezham.com
      APP_ACCOUNTS_URL: https://qa.accounts.vezham.com
      APP_BUSINESS_URL: https://qa.business.vezham.com
      APP_HQ_URL: https://qa.hq.vezham.com
      APP_IS_SANDBOX: true
      APP_SANDBOX_API_URL: https://sandbox.api.vezham.com
      APP_DC_API_URL: https://{DC}.api.vezham.com

  preview:
    name: dc/preview
    if: ${{ inputs.CALLER == 'deploy/preview' || inputs.CALLER == '-scheduler' }}
    uses: vezham/v0xFE-deployer/.github/workflows/business.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.BUSINESS_PREVIEW_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/preview
      APP_NAME: business
      APP_API_URL: https://dev.api.vezham.com
      APP_IAM_URL: https://preview.iam.vezham.com
      APP_ACCOUNTS_URL: https://preview.accounts.vezham.com
      APP_BUSINESS_URL: https://preview.business.vezham.com
      APP_HQ_URL: https://preview.hq.vezham.com
      APP_IS_SANDBOX: true
      APP_SANDBOX_API_URL: https://sandbox.api.vezham.com
      APP_DC_API_URL: https://{DC}.api.vezham.com
      
  live:
    name: dc/live
    if: ${{ inputs.CALLER == 'deploy/live' || inputs.CALLER == '-scheduler' }}
    uses: vezham/v0xFE-deployer/.github/workflows/business.helper.yml@timeline
    secrets:
      GCP_SA_KEY: ${{ secrets.BUSINESS_LIVE_GCP_SA_KEY }}
    with:
      GIT_BRANCH: deploy/live
      APP_NAME: business
      APP_API_URL: https://api.vezham.com
      APP_IAM_URL: https://iam.vezham.com
      APP_ACCOUNTS_URL: https://accounts.vezham.com
      APP_BUSINESS_URL: https://business.vezham.com
      APP_HQ_URL: https://hq.vezham.com
      APP_IS_SANDBOX: false
      APP_SANDBOX_API_URL: https://sandbox.api.vezham.com
      APP_DC_API_URL: https://{DC}.api.vezham.com
