name: hq-mock | deployer

on:
  workflow_call:
    inputs:
      CALLER:
        required: true
        type: string

jobs:
  tva:
    name: dc/TVA
    if: ${{ inputs.CALLER == 'timeline' }}
    uses: vezham/v0xFE-deployer/.github/workflows/hq-mock.helper.yml@timeline
    secrets:
      VERCEL_SA_KEY: ${{ secrets.HQ_MOCK_TVA_VERCEL_SA_KEY }}
    with:
      GIT_BRANCH: ${{ inputs.CALLER }}
      IS_DEBUG: true
      IS_BETA: true
      APP_NAME: hq-mock
