name: static_cdn | helper

on:
  workflow_call:
    secrets:
      GCP_SA_KEY:
        required: true
    inputs:
      GIT_REPO:
        required: false
        type: string
      GIT_BRANCH:
        required: false
        type: string
      IS_PREVIEW:
        required: false
        type: boolean
        default: false
      IS_DEBUG:
        required: false
        type: boolean
        default: false
      IS_BETA:
        required: false
        type: boolean
        default: false
      APP_NAME:
        type: string
      # wjdlz/NOTE: custom-fields

env:
  REPO: ${{ inputs.GIT_REPO || 'vezham/v0xFE-apps-cdns' }}
  BRANCH: ${{ inputs.GIT_BRANCH || 'timeline' }}
  CI_DIR: ../../v/bin/ci
  CI_TOKEN_URL : https://lab5-ic-web-vezham.web.app/ci/gcp
  ENTRY_POINT: ./apps_cdns/static_cdn
  DX_APP_PATH: apps_cdns/static_cdn
  DX_APP_NAME: static_cdn
  NX_APP_NAME: static_cdn

jobs:
  build_and_deploy:
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [9.6.0]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ env.ENTRY_POINT }}
    steps:
      - name: checkout | ${{ env.REPO }}@${{ env.BRANCH }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.BRANCH }}
        
      # wjdlz/TODO: ci-setup | fetch-credentials - via vezham CI host
      # - name: ci-setup | fetch-credentials
      #   id: fetch-credentials
      #   run: |
      #     TOKEN=$(curl -s ${{ env.CI_TOKEN_URL }})
      #     {
      #         echo "token=<<EOF"
      #         curl -s ${{ env.CI_TOKEN_URL }}
      #         echo "EOF"
      #     } >> "$GITHUB_OUTPUT"

      - name: ci-setup | fetch $ENV_TOKENS
        id: extract-credentials
        shell: bash
        run: |
          ${{ env.CI_DIR }}/firebase/fetch-credentials.sh ${{ env.CI_TOKEN_URL }} "$GITHUB_OUTPUT"

      # - name: ci-setup | extract $ENV_TOKENS
      #   id: extract-credentials
      #   shell: bash
      #   run: |
      #     # wjdlz/NOTE: save token to temporary file
      #     echo '${{ secrets.GCP_SA_KEY }}' > token.json
          
      #     # wjdlz/NOTE: extract & mask credentials
      #     ${{ env.CI_DIR }}/firebase/extract-credentials.sh token.json "$GITHUB_OUTPUT"
          
      #     # wjdlz/NOTE: clean up
      #     rm token.json

      - name: ci-setup | gen $ENV_TOKENS
        id: gen-env-tokens
        env:
          GCP_PROJECT_ID: ${{ steps.extract-credentials.outputs.GCP_PROJECT_ID }}
        run: |
          {
            echo "GCP_PROJECT_ID=$GCP_PROJECT_ID"
          } >> $GITHUB_ENV

      - name: ci-setup | short-sha
        uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: ci-setup | $SHA
        run: |
          echo 'SHA=${{ steps.short-sha.outputs.sha }}' >> $GITHUB_ENV

      - name: ci-setup | gen DX_APP_URL
        id: gen-dx-app-url
        # echo "DX_APP_URL=${{ env.DX_APP_NAME }}-${{ env.BRANCH }}-${{ env.SHA }}-${{ github.actor }}.ui.dx.tva.v0x.in" >> $GITHUB_ENV
        run: |
          echo "DX_APP_URL=${{ env.DX_APP_NAME }}-${{ env.BRANCH }}-${{ env.SHA }}" >> $GITHUB_ENV

      - name: setup | pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: setup | node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: setup | pnpm install
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: setup | .env vars
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: ${{ env.ENTRY_POINT }}
          envkey_V_IS_PREVIEW: ${{ inputs.IS_PREVIEW }}
          envkey_V_IS_DEBUG: ${{ inputs.IS_DEBUG }}
          envkey_V_IS_BETA: ${{ inputs.IS_BETA }}
          envkey_V_APP_NAME: ${{ inputs.APP_NAME }}
        
      - name: setup | build
        run: npm run build --name=${{ env.NX_APP_NAME }}

      - name: logs | archive npm failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: ~/.npm/_logs

      - name: cloud-setup | firebase
        # shell: bash
        run: bash ${{ env.CI_DIR }}/firebase/main.sh ${{ env.DX_APP_PATH }}

      - name: cloud-cli | gcp/preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: gcp-preview
        with:
          expires: 30d
          channelId: ${{ env.DX_APP_URL }}
          repoToken: ${{ env.GITHUB_TOKEN }}
          projectId: ${{ env.GCP_PROJECT_ID }}
          firebaseServiceAccount: ${{ secrets.GCP_SA_KEY }}
          # entryPoint: ${{ env.ENTRY_POINT }}

      - name: setup | fetch preview url
        uses: mad9000/actions-find-and-replace-string@5
        id: gcp-preview-url
        with:
          source: ${{ steps.gcp-preview.outputs.details_url }}
          find: '***'
          replace: ${{ env.GCP_PROJECT_ID }}

      - name: cloud-cli | gcp/live
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: gcp
        with:
          # expires: 30d
          channelId: live
          # repoToken: ${{ env.GITHUB_TOKEN }}
          projectId: ${{ env.GCP_PROJECT_ID }}
          firebaseServiceAccount: ${{ secrets.GCP_SA_KEY }}
          # entryPoint: ${{ env.ENTRY_POINT }}

      # wjdlz/NOTE: cloud-setup | vercel - alternative

      - name: deployer | create commit comment
        uses: peter-evans/commit-comment@v1
        # - https://${{ env.DX_APP_URL }}
        with:
          body: |
            🚀 Build deployed successfully to the following URLs
            - [Preview](${{ steps.gcp-preview-url.outputs.value }}) - ${{ steps.gcp-preview.outputs.expire_time }}
            - [Live Demo](https://${{ env.GCP_PROJECT_ID }}.web.app)
